version: '3.9'

services:
  minio:
    image: minio/minio
    container_name: minio_s3
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=obai9Szm6zF7XpWr6UTQ
      - MINIO_SECRET_KEY=vNZBQjoCigmI6QDhMIG2BQhm6Vgx4WFGqQkhAdZ4
    volumes:
      - ./minio:/data
    command: server /minio

  api:
    image: romjiik/ml_ops_api
    container_name: api
    restart: always
    depends_on:
      - minio
    ports:
      - "8080:8080"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=obai9Szm6zF7XpWr6UTQ
      - MINIO_SECRET_KEY=vNZBQjoCigmI6QDhMIG2BQhm6Vgx4WFGqQkhAdZ4
    volumes:
      - ./api:/app
    command: sh init_minio_and_dvc.sh

